const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.Timer,
		C3.Behaviors.bound,
		C3.Behaviors.LOS,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.custom,
		C3.Plugins.Particles,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Behaviors.scrollto,
		C3.Plugins.shadowlight,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Behaviors.MoveTo,
		C3.Plugins.Audio,
		C3.Plugins.TextBox,
		C3.Behaviors.Pathfinding,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.shadowlight.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.custom.Acts.AcceleratePos,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.custom.Acts.AccelerateAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.custom.Exps.MovingAngle,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Behaviors.EightDir.Exps.Speed,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.AngleWithin,
		C3.Behaviors.EightDir.Exps.MovingAngle,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Behaviors.custom.Acts.SetAngleOfMotion,
		C3.Behaviors.custom.Exps.Speed,
		C3.Behaviors.custom.Acts.Stop,
		C3.Behaviors.custom.Acts.SetEnabled,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Behaviors.LOS.Acts.SetCone,
		C3.Behaviors.custom.Cnds.CompareSpeed,
		C3.Behaviors.Pathfinding.Exps.MovingAngle,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Behaviors.Pathfinding.Cnds.CompareSpeed,
		C3.Behaviors.Pathfinding.Acts.SetSpeed,
		C3.Behaviors.Pathfinding.Cnds.IsCalculatingPath,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Acts.SetAcc,
		C3.Behaviors.custom.Acts.PushOutSolid,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.TiledBg.Cnds.CompareHeight,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Tilemap.Exps.TileToPositionX,
		C3.Plugins.Tilemap.Exps.TileToPositionY,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Tilemap.Acts.SetTile,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.Focus,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.shadowcaster.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Tween.Acts.TweenTwoProperties
	];
};
self.C3_JsPropNameTable = [
	{onItem: 0},
	{health: 0},
	{maxHealth: 0},
	{"8Direction": 0},
	{Timer: 0},
	{BoundToLayout: 0},
	{Player: 0},
	{canShoot: 0},
	{firerate: 0},
	{whichBarrel: 0},
	{ammoMagazine: 0},
	{ammoMagazineCapacity: 0},
	{ammoReserves: 0},
	{reloading: 0},
	{LineOfSight: 0},
	{PlayerBody: 0},
	{playerFeet: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Solid: 0},
	{ShadowCaster: 0},
	{walls: 0},
	{backgrounds: 0},
	{damage: 0},
	{type: 0},
	{ID: 0},
	{Custom: 0},
	{bullet: 0},
	{behaviorState: 0},
	{target: 0},
	{chaseSpeed: 0},
	{wanderSpeed: 0},
	{hp: 0},
	{Alive: 0},
	{distanceFromPlayer: 0},
	{zombie: 0},
	{deadBodies: 0},
	{running: 0},
	{headlightsOn: 0},
	{gas: 0},
	{doors: 0},
	{car: 0},
	{roads: 0},
	{gunSmoke: 0},
	{fx_shatter: 0},
	{Pathfinding_Avoid: 0},
	{source: 0},
	{loudness: 0},
	{Fade: 0},
	{sound: 0},
	{cursor: 0},
	{hotkeys: 0},
	{hotkeyHighlighter: 0},
	{blood: 0},
	{spawnTime: 0},
	{spawnCount: 0},
	{zombieSpawner: 0},
	{grass: 0},
	{Browser: 0},
	{closedAngle: 0},
	{openAngle: 0},
	{closed: 0},
	{Tween: 0},
	{door: 0},
	{floorDecorations: 0},
	{HpBase: 0},
	{HpBar: 0},
	{HpBarCap: 0},
	{hurtsPlayer: 0},
	{hurtsEnemy: 0},
	{Source: 0},
	{meleeHitbox: 0},
	{ScrollTo: 0},
	{camera: 0},
	{ShadowLight: 0},
	{vision: 0},
	{interactDistance: 0},
	{playerInventory: 0},
	{ammo: 0},
	{WallSprites: 0},
	{MoveTo: 0},
	{droppedMag: 0},
	{loot: 0},
	{maxLoot: 0},
	{lootSpawner: 0},
	{Audio: 0},
	{light: 0},
	{darkness: 0},
	{CellBars: 0},
	{LootContainer: 0},
	{TitleBackground: 0},
	{whichButton: 0},
	{Menu_Button: 0},
	{Menu_ButtonText: 0},
	{Menu_Alias: 0},
	{Pathfinding: 0},
	{zombies: 0},
	{visionConnected: 0},
	{ZombieLimit: 0},
	{zombieID: 0},
	{ZombieSpawnerID: 0},
	{zombieCount: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	PlayerBody: class extends self.ISpriteInstance {},
	playerFeet: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	walls: class extends self.ITilemapInstance {},
	backgrounds: class extends self.ITilemapInstance {},
	bullet: class extends self.ISpriteInstance {},
	zombie: class extends self.ISpriteInstance {},
	deadBodies: class extends self.ISpriteInstance {},
	car: class extends self.ISpriteInstance {},
	roads: class extends self.ITilemapInstance {},
	gunSmoke: class extends self.IParticlesInstance {},
	fx_shatter: class extends self.ISpriteInstance {},
	Pathfinding_Avoid: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	cursor: class extends self.ISpriteInstance {},
	hotkeys: class extends self.ITilemapInstance {},
	hotkeyHighlighter: class extends self.ISpriteInstance {},
	blood: class extends self.ISpriteInstance {},
	zombieSpawner: class extends self.ISpriteInstance {},
	grass: class extends self.ITiledBackgroundInstance {},
	Browser: class extends self.IInstance {},
	door: class extends self.ISpriteInstance {},
	floorDecorations: class extends self.ISpriteInstance {},
	HpBase: class extends self.ISpriteInstance {},
	HpBar: class extends self.ITiledBackgroundInstance {},
	HpBarCap: class extends self.ISpriteInstance {},
	meleeHitbox: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	vision: class extends self.ISpriteInstance {},
	interactDistance: class extends self.ISpriteInstance {},
	playerInventory: class extends self.IArrayInstance {},
	ammo: class extends self.ITextInstance {},
	WallSprites: class extends self.ISpriteInstance {},
	droppedMag: class extends self.ISpriteInstance {},
	loot: class extends self.ISpriteInstance {},
	lootSpawner: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	light: class extends self.ISpriteInstance {},
	darkness: class extends self.ISpriteInstance {},
	CellBars: class extends self.ISpriteInstance {},
	LootContainer: class extends self.ISpriteInstance {},
	TitleBackground: class extends self.ISpriteInstance {},
	Menu_Button: class extends self.ISpriteInstance {},
	Menu_ButtonText: class extends self.ITextInstance {},
	Menu_Alias: class extends self.ITextInputInstance {},
	zombies: class extends self.ISpriteInstance {},
	visionConnected: class extends self.ISpriteInstance {}
}