const games = [
    {
        name:'Hands of Hell',
        link:'/games',
        thumbnail:'',
        descriptionShort:'',
        descriptionLong:'',
    },
    {
        name:'Kori',
        link:'games/kori',
        thumbnail:'',
        descriptionShort:'',
        descriptionLong:'',
    },
    {
        name:'City Smasher',
        link:'',
        thumbnail:'',
        descriptionShort:'',
        descriptionLong:'',
    },
    {
        name:'Cavern of Souls',
        link:'games/cavern-of-souls',
        thumbnail:'',
        descriptionShort:'',
        descriptionLong:'',
    },
    {
        name:'Binary Spaces',
        link:'games/binary-spaces',
        thumbnail:'',
        descriptionShort:'',
        descriptionLong:'',
    },
    {
        name:'The Void',
        link:'',
        thumbnail:'',
        descriptionShort:'',
        descriptionLong:'',
    },
    {
        name:'Ix n Terra',
        link:'',
        thumbnail:'',
        descriptionShort:'',
        descriptionLong:'',
    },
]

const apps = [
    {
        name:'UWU',
        link:'apps/custom-homepage',
        thumbnail:'',
        descriptionShort:'',
        descriptionLong:'',
    },
    {
        name:'Precision Kitchen',
        link:'https://precision.kitchen',
        thumbnail:'',
        descriptionShort:'',
        descriptionLong:'',
    },
    {
        name:'Blah Blah Blog',
        link:'apps/blah-blah-blog',
        thumbnail:'',
        descriptionShort:'',
        descriptionLong:'',
    },
    {
        name:'Müz',
        link:'apps/muz',
        thumbnail:'',
        descriptionShort:'',
        descriptionLong:'',
    },
    {
        name:'Resume Magic',
        link:'apps/resume-magic',
        thumbnail:'',
        descriptionShort:'',
        descriptionLong:'',
    },
    {
        name:'Journal.io',
        link:'',
        thumbnail:'',
        descriptionShort:'',
        descriptionLong:'',
    },
    {
        name:'Virtual Business Card',
        link:'',
        thumbnail:'',
        descriptionShort:'',
        descriptionLong:'',
    },
    {
        name:'Asset Repository',
        link:'',
        thumbnail:'',
        descriptionShort:'Just a place for me to dump all the assets I made.',
        descriptionLong:'',
    },
    {
        name:'Cheat Sheets',
        link:'',
        thumbnail:'',
        descriptionShort:'Just a place for me to document my knowledge and understanding of different programming languages, tools, libraries, or anything else really.',
        descriptionLong:'',
    },
]